export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_ALL_TYPES = "GET_ALL_TYPES"

export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_COUNTRY_DETAIL';
export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME'
// export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME'