export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";

export const GET_ALL_TYPES = "GET_ALL_TYPES"
export const FILTER_BY_TYPE= 'FILTER_BY_TYPE'
export const FILTER_BY_SOURCE= 'FILTER_BY_SOURCE'

export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_COUNTRY_DETAIL';

export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME'
export const DELETE_STATE = 'DELETE_STATE'


export const ORDER_BY_NAME= 'ORDER_BY_NAME'
export const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK'

export const POST_POKEMON= 'POST_POKEMON'


export const ORDER_BY_DEFENSE = 'ORDER_BY_DEFENSE'

